version: '3.8'

networks:
  app:
    driver: bridge

services:

  client:
    container_name: client
    build: client
    restart: unless-stopped
    networks:
      app: { }

  database:
    container_name: database
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-app}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    networks:
      app: { }
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build: server
    restart: unless-stopped
    volumes:
      - ./server:/app:rw
    environment:
      APP_DEBUG: ${APP_DEBUG:-"false"}
      APP_KEY: ${APP_KEY:-0}
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: ${DB_NAME:-app}
      DB_USERNAME: ${DB_USERNAME:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      JWT_SECRET: ${AUTH_KEY:-0}
    networks:
      app: { }
    depends_on:
      - database

  proxy:
    container_name: proxy
    build: proxy
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      app: { }
    depends_on:
      - backend
      - client
    ports:
      - "80:80"
