export const inputStyleConfig = {
  fontFamily: 'Open Sans',
  valueColor: '#2d3748',
  valueFontWeight: 500,
  placeholderColor: '#cbd5e0',
  placeholderDisabledColor: '#cbd5e0',
  labelColor: '#a0aec0',
  labelFontWeight: 500,
  helperTextColor: '#a0aec0',
  helperTextFontWeight: 400,
  helperTextFontSize: '12px',
  borderColor: '#edf2f7',
  borderRadius: '6px',
  backgroundColor: '#ffffff',
  backgroundDisabledColor: '#edf2f7',
  focusBorderColor: '#3385ff',
  filledBackgroundColor: '#e5f0ff',
  filledFontColor: '#3385ff',
  searchBackgroundColor: '#f7fafc',
  iconColor: '#cbd5e0',
  errorColor: '#f16063',
  successColor: '#66cb9f',
}

export const inputStyleConfigWhiteOutline = {
  fontFamily: 'Inter',
  valueColor: '#FFFFFF',
  valueFontWeight: 400,
  placeholderColor: '#FFFFFF',
  placeholderDisabledColor: '#FFFFFF',
  labelColor: '#FFFFFF',
  labelFontWeight: 700,
  helperTextColor: '#a0aec0',
  helperTextFontWeight: 400,
  helperTextFontSize: '12px',
  borderColor: '#76ACFB',
  borderRadius: '8px',
  backgroundColor: 'transparent',
  backgroundDisabledColor: '#edf2f7',
  focusBorderColor: '#E2E8F0',
  filledBackgroundColor: '#e5f0ff',
  filledFontColor: '#3385ff',
  searchBackgroundColor: '#f7fafc',
  iconColor: '#cbd5e0',
  errorColor: '#f16063',
  successColor: '#66cb9f',
}
