export const textAreaStyleConfig = {
  fontFamily: 'Open Sans',
  valueColor: '#a0aec0',
  valueFontWeight: 500,
  placeholderColor: '#a0aec0',
  backgroundColor: '#ffffff',
  labelColor: '#2d3748',
  labelFontWeight: 500,
  helperTextColor: '#a0aec0',
  helperTextFontWeight: 400,
  borderColor: '#edf2f7',
  borderRadius: '8px',
  focusBorderColor: '#3385ff',
  errorColor: '#f16063',
}
